In [1]:
import pandas as pd

metadata = pd.read_csv("Dataset/drive-download/metadata/GTEx_Analysis_v10_Annotations_SampleAttributesDS.txt", sep="\t")
metadata.head()

D:\temp\ipykernel_15492\702601831.py:3: DtypeWarning: Columns (0: SMGTC) have mixed types. Specify dtype option on import or set low_memory=False.
  metadata = pd.read_csv("Dataset/drive-download/metadata/GTEx_Analysis_v10_Annotations_SampleAttributesDS.txt", sep="\t")

,SAMPID,SMATSSCR,SMCENTER,SMPTHNTS,SMRIN,SMTS,SMTSD,SMUBRID,SMTSISCH,SMTSPAX,...,SMSHRTRT,SMSMRDHQ,SMSMRTHQ,SMPRERDHQ,SMPRERTHQ,SMSMGNDT,SMPREGNDT,SMRDLNMN,SMRDLNMD,SMRDLNSD
0,BMS-X4LF-0126-SM-4JBHL,NaN,B1,NaN,7.5,Thyroid,Thyroid,UBERON:0002046,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BMS-X4LF-0226-SM-4JBJ3,NaN,B1,NaN,6.9,Blood Vessel,Artery - Pulmonary,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BMS-X4LF-0326-SM-4JBIR,NaN,B1,NaN,7.4,Muscle,Muscle - Skeletal,UBERON:0011907,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BMS-X4LF-0426-SM-4JBIS,NaN,B1,NaN,7.1,Skin,Skin - Sun Exposed (Lower leg),UBERON:0004264,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BMS-X4LF-0526-SM-4JBHX,NaN,B1,NaN,8.8,Adrenal Gland,Adrenal Gland,UBERON:0002369,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df = pd.read_csv("Dataset/result/ML_Dataset/expression_dataframe.csv", index_col=0)
df.fillna(0, inplace=True)

,GTEX-1117F-0226-SM-5GZZ7,GTEX-111CU-1826-SM-5GZYN,GTEX-111FC-0226-SM-5N9B8,GTEX-111VG-2326-SM-5N9BK,GTEX-111YS-2426-SM-5GZZQ,GTEX-1122O-2026-SM-9YFMG,GTEX-1128S-2126-SM-5H12U,GTEX-113IC-0226-SM-5HL5C,GTEX-117XS-2426-SM-GHWOR,GTEX-117YX-2226-SM-5EGJJ,...,GTEX-ZVZQ-0006-SM-51MR8,GTEX-ZXES-0005-SM-57WCB,GTEX-ZXG5-0005-SM-57WCN,GTEX-ZY6K-0006-SM-GRR18,GTEX-ZYFC-0006-SM-HL9SK,GTEX-ZYFD-0005-SM-HL9SL,GTEX-ZYT6-0006-SM-HL9SM,GTEX-ZYVF-0005-SM-HL9SN,GTEX-ZYW4-0006-SM-HAUXL,GTEX-ZZPU-0006-SM-HL9SO
gene,,,,,,,,,,,,,,,,,,,,,
2,8.484106,9.129736,9.645572,9.785400,9.192463,8.784782,9.185770,9.388825,9.288859,9.331855,...,1.647084,0.842899,0.703190,0.570968,0.994857,0.583495,0.906227,1.028385,0.800856,0.479807
10,0.375284,0.211887,0.080656,0.251822,0.099924,0.204160,0.223946,0.118037,0.295305,0.000000,...,0.000000,0.092306,0.000000,0.000000,0.000000,0.000000,0.088060,0.290523,0.038040,0.000000
15,0.528751,0.751554,0.118592,0.463501,0.253807,0.094847,0.035653,0.236155,0.094493,0.135375,...,0.326413,0.739388,0.507312,0.261313,0.242835,0.260474,0.357659,0.321121,0.213179,0.647839
16,5.512186,6.203990,5.535014,5.456754,5.481735,5.538737,5.626807,5.773991,5.748668,5.523841,...,3.763018,2.560304,3.961123,1.821245,3.594943,3.771072,3.882506,2.884600,1.984957,1.509711
18,3.171679,2.794170,2.016076,2.587653,2.654406,2.401357,2.190795,2.288187,2.365911,2.798988,...,1.337745,3.880539,2.669201,2.083397,1.182139,1.597565,1.700795,0.517517,1.315166,2.718263
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122526777,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.141493,0.000000,0.000000,0.000000,0.000000
123956252,7.964104,8.443946,8.100647,7.823112,8.021385,8.661571,8.677913,8.285014,8.271776,7.256048,...,5.350610,5.931031,5.468551,5.091463,5.084234,5.934488,5.450439,4.959084,4.471402,5.360368
124901481,6.093723,7.086295,6.394283,6.741683,5.938321,6.557062,6.308097,6.553019,6.349126,6.531433,...,5.520850,5.423582,4.974360,6.300526,4.201681,4.774713,5.723113,4.523725,3.983140,6.003688
125467750,6.231123,6.191148,6.215081,5.481958,5.832260,5.892359,6.257833,5.725703,5.822090,6.528059,...,1.059064,1.584987,0.588398,1.656231,1.140681,0.259482,1.071783,0.644070,1.873463,3.125028
128966744,0.296698,0.000000,0.364279,0.257522,0.527011,0.061861,0.175117,0.698194,0.541833,0.235846,...,0.033349,0.000000,0.000000,0.000000,0.130340,0.000000,0.000000,0.000000,0.014737,0.000000

In [3]:
meta_filtered = metadata.loc[metadata["SAMPID"].isin(df.columns), ["SAMPID", "SMCENTER", "SMNABTCH", "SMGEBTCH", "SMTSD"]]
meta_filtered["SUBJID"] = meta_filtered["SAMPID"].str.split("-").str[:2].str.join("-")
meta_filtered = meta_filtered.set_index("SAMPID").reindex(df.columns)
meta_filtered.index.name = "SAMPID"
meta_filtered = meta_filtered.reset_index()

meta_filtered

,SAMPID,SMCENTER,SMNABTCH,SMGEBTCH,SMTSD,SUBJID
0,GTEX-1117F-0226-SM-5GZZ7,B1,BP-43693,LCSET-4804,Adipose - Subcutaneous,GTEX-1117F
1,GTEX-111CU-1826-SM-5GZYN,B1,BP-43783,LCSET-4804,Adipose - Subcutaneous,GTEX-111CU
2,GTEX-111FC-0226-SM-5N9B8,B1,BP-43989,LCSET-4904,Adipose - Subcutaneous,GTEX-111FC
3,GTEX-111VG-2326-SM-5N9BK,B1,BP-43989,LCSET-4904,Adipose - Subcutaneous,GTEX-111VG
4,GTEX-111YS-2426-SM-5GZZQ,B1,BP-43693,LCSET-4805,Adipose - Subcutaneous,GTEX-111YS
...,...,...,...,...,...,...
6759,GTEX-ZYFD-0005-SM-HL9SL,C1,BP-38188,LCSET-13764,Whole Blood,GTEX-ZYFD
6760,GTEX-ZYT6-0006-SM-HL9SM,C1,BP-38188,LCSET-13764,Whole Blood,GTEX-ZYT6
6761,GTEX-ZYVF-0005-SM-HL9SN,C1,BP-38188,LCSET-13764,Whole Blood,GTEX-ZYVF
6762,GTEX-ZYW4-0006-SM-HAUXL,C1,BP-38291,"LCSET-13283,LCSET-13451",Whole Blood,GTEX-ZYW4
6763,GTEX-ZZPU-0006-SM-HL9SO,B1,BP-38553,LCSET-13764,Whole Blood,GTEX-ZZPU

In [4]:
meta_filtered["SMTSD"].unique()

<StringArray>
[      'Adipose - Subcutaneous',              'Artery - Tibial',
      'Breast - Mammary Tissue', 'Cells - Cultured fibroblasts',
           'Esophagus - Mucosa',                         'Lung',
            'Muscle - Skeletal',               'Nerve - Tibial',
                      'Thyroid',                  'Whole Blood']
Length: 10, dtype: str

In [5]:
mask = meta_filtered["SMTSD"] == "Thyroid"
mask

0       False
1       False
2       False
3       False
4       False
        ...
6759    False
6760    False
6761    False
6762    False
6763    False
Name: SMTSD, Length: 6764, dtype: bool

In [6]:
meta_filtered.loc[mask.values, "SMGEBTCH"].values

<StringArray>
[          'LCSET-12979',            'LCSET-4804',            'LCSET-4804',
            'LCSET-4904',            'LCSET-4804',            'LCSET-4904',
            'LCSET-4805', 'LCSET-4766,LCSET-4797',            'LCSET-4417',
            'LCSET-4764',
 ...
            'LCSET-4903',            'LCSET-4804',            'LCSET-4906',
            'LCSET-4804',            'LCSET-4796',            'LCSET-4635',
            'LCSET-4903',            'LCSET-4804',            'LCSET-4804',
            'LCSET-4804']
Length: 684, dtype: str

In [7]:
df.loc[:, mask.values]

SAMPID,GTEX-1117F-1426-SM-H65ZH,GTEX-111CU-0226-SM-5GZXC,GTEX-111FC-1026-SM-5GZX1,GTEX-111VG-0526-SM-5N9BW,GTEX-111YS-0726-SM-5GZY8,GTEX-1122O-0226-SM-5N9DA,GTEX-1128S-0126-SM-5H12S,GTEX-113JC-0126-SM-5EGJW,GTEX-117XS-0526-SM-5987Q,GTEX-117YW-0126-SM-5EGGN,...,GTEX-ZY6K-0226-SM-5MR7Z,GTEX-ZYFC-0926-SM-5GZWW,GTEX-ZYFD-0826-SM-5NQ9A,GTEX-ZYFG-0626-SM-5GZYA,GTEX-ZYT6-0426-SM-5GID3,GTEX-ZYVF-1126-SM-5E458,GTEX-ZYW4-1126-SM-5MR6A,GTEX-ZYY3-1926-SM-5GZXS,GTEX-ZZ64-0126-SM-5GZXA,GTEX-ZZPU-1326-SM-5GZWS
gene,,,,,,,,,,,,,,,,,,,,,
2,9.510869,8.651988,7.698774,8.293968,9.053337,8.309717,9.315224,8.184563,8.788311,7.441400,...,8.097716,8.796458,8.211231,8.200889,8.348210,8.631501,9.156703,8.994713,8.701691,9.305410
10,0.000000,0.214418,0.000000,0.000000,0.110238,0.000000,0.000000,0.131188,0.000000,0.159601,...,0.000000,0.067507,0.000000,0.287163,0.185835,0.000000,0.000000,0.000000,0.000000,0.115916
15,0.621794,0.446689,1.121314,0.820982,0.535660,0.523291,0.648235,0.843439,0.898306,0.468284,...,0.494083,0.598295,0.641552,0.311098,0.495371,0.976807,0.742493,0.782969,0.383593,0.484304
16,6.194885,7.524510,6.381418,5.181941,6.089348,6.524915,6.282447,6.049681,6.079478,6.170646,...,7.540787,6.842639,6.753337,6.762282,6.246416,6.400533,5.687906,5.800838,7.380409,6.360861
18,4.458854,3.993330,5.967459,3.535207,4.363458,4.293473,4.548998,4.543762,4.746318,5.293996,...,4.887949,5.696269,3.700728,5.220872,5.539869,4.481641,3.794322,3.386230,4.661807,3.673443
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122526777,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.208901
123956252,7.331096,7.136776,7.152183,6.834736,6.850874,6.890094,7.495279,7.468974,7.564470,7.163529,...,6.556325,7.378564,7.211762,7.266955,7.196656,7.187411,6.926415,6.788255,7.320160,6.894975
124901481,6.517184,7.041845,7.047298,6.114754,6.259482,6.595745,6.698635,6.366310,6.768462,6.645030,...,7.191612,6.755809,6.576847,6.781806,6.911620,7.432358,6.211622,6.572990,6.799968,6.283187
125467750,7.723545,8.156569,6.271414,5.983345,6.265411,6.912901,8.753735,8.932365,8.030491,7.887440,...,6.401673,7.498091,9.048214,6.498090,6.905844,8.516732,8.445151,6.147209,7.695583,6.648012
128966744,0.166848,0.035103,0.561222,0.100750,0.126365,0.106859,0.429191,0.101867,0.060523,0.292496,...,0.776129,0.564245,0.366079,0.225598,0.144901,0.164539,0.263376,0.225226,0.388019,0.215052

In [12]:
len(meta_filtered["SUBJID"].unique())

945

In [ ]:
def within_tissue_batch_silhouette(data, metadata, batch_key, tissue_key="SMTSD", n_pcs=30, min_samples=50):
    from sklearn.decomposition import PCA
    from sklearn.metrics import silhouette_score
    import numpy as np

    scores = {}
    weights = {}

    for tissue in metadata[tissue_key].unique():
        tissue_mask = (metadata[tissue_key] == tissue).values

        # Drop samples with NaN in the batch key
        valid_mask = tissue_mask & metadata[batch_key].notna().values

        n_samples = valid_mask.sum()
        n_batches = metadata.loc[valid_mask, batch_key].nunique()

        if n_samples < min_samples or n_batches < 2:
            continue

        tissue_data = data.loc[:, valid_mask]
        pca = PCA(n_components=min(n_pcs, n_samples - 1))
        pcs = pca.fit_transform(tissue_data.T)

        batch_labels = metadata.loc[valid_mask, batch_key].values
        score = silhouette_score(pcs, batch_labels)

        scores[tissue] = score
        weights[tissue] = n_samples

    total = sum(weights.values())
    weighted_score = sum(scores[t] * weights[t] / total for t in scores)

    return weighted_score, scores

# Compare batch variables properly
geo_score, geo_per_tissue = within_tissue_batch_silhouette(df, meta_filtered, "SUBJID")
# na_score,  na_per_tissue  = within_tissue_batch_silhouette(df, meta_filtered, "SMNABTCH")
# sm_score, sm_per_tissue = within_tissue_batch_silhouette(df, meta_filtered, "SMCENTER")

print(f"SMGEBTCH: {geo_score:.3f}")
# print(f"SMNABTCH: {na_score:.3f}")
# print(f"SMCENTER:   {sm_score:.3f}")

ValueError: Number of labels is 714. Valid values are 2 to n_samples - 1 (inclusive)